version: "3.8"
services:
  api:
    container_name: api
    build: .
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: .
        target: /api
    depends_on:
      - db
  db:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: nestjs_db
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: nestjs_db
      MYSQL_ROOT_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf